### PR TITLE
WIP: start merging things

### PR DESCRIPTION
**Pull request by jmfayard**
I removed the gradle-versions-plugins and a bunch of obsolete stuff
so that we can start integrating the "experimental" - I mean the new updater with the rest of the plugin

### CODE REVIEW

**Comment by LouisCAD** [comment]
Checking this in IDE.

**Comment by LouisCAD** [comment]
Is there any reason you didn't base it off the latest master branch?

**Comment by LouisCAD** [comment]
Now that the plugin is sorting out the updates by stability level, I don't think we still need `RefreshVersionsExtension` at all.

Regarding upgrading from a Gradle task, I opened #151 for it.

**Comment by jmfayard** [comment]
let's talk about it in Copenhagen

**Pull request closed without merging**
