### PR TITLE
Added two new kotest modules

### PR DESCRIPTION
**Pull request by sksamuel**
- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description

Added two new kotest modules.

### CODE REVIEW

**Comment by jmfayard** [comment]
@sksamuel I'm sorry, the pull request has to be made against the branch `develop`
The branch `master` contains the published code, not the latest code

**Comment by LouisCAD** [comment]
We're about to publish an updated contributing guide (hadn't been revisited in a while), that will cover how to submit library module updates. I'll let you know when it's updated. Hopefully this week.

**Comment by sksamuel** [comment]
Ah I see.

**Comment by jmfayard** [comment]
Added to https://github.com/jmfayard/refreshVersions/issues/238
We will get back to it when we have a better way to add a dependency

**Pull request closed without merging**
