### PR TITLE
[Issue-621] Updated docs for Import -> Link Gradle Project terminology

### LINKED ISSUE #621: Documentation: Update terminology for latest IntelliJ version
- [x] I have read the [guidelines for submitting issues](https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/)
## 🐛 Describe the bug
Terminology change inside IntelliJ for including a new Gradle project.

## ⚠️ Current behavior
The [Dev environment documentation](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-env/#import-the-plugins-gradle-project) states that you should Select "Import Gradle Project"

## ✅ Expected behavior
As of at least IntelliJ 2022.2.1, the menu option has changed to "Link Gradle Project"

## 💣 Steps to reproduce
Follow  the [Dev environment documentation](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-env/#import-the-plugins-gradle-project) and compare to the latest IntelliJ

## 📱 Tech info
N/A

### PR DESCRIPTION
**Pull request by thederputy**
Hello/bonjour, this is a minor documentation update to the dev set up page.

## What?

Resolves #621

Minor documentation update to account for the change in terminology in newer IntelliJ versions (since at least 2022.1)

## Why?

To help new contributors to the project.

## How?

Took a new screenshot on the latest IntelliJ

## Testing?

I have yet to test the changes, but I'm pushing this early so that @LouisCAD can review for the next release.

### CODE REVIEW

**Comment by LouisCAD** [comment]
WOW! The new screenshot is 18.6kB larger! (That's not really a problem, it's not like a landing page 😄)

**Review by LouisCAD — APPROVED** [review]
Perfect, thank you!

**Comment by thederputy** [comment]
> WOW! The new screenshot is 18.6kB larger! (That's not really a problem, it's not like a landing page 😄)

Oops, I forgot to run it through [tinypng](https://tinypng.com/) first.

**Comment by LouisCAD** [comment]
Same quality? If so, feel free to send another PR 🙂

**Comment by LouisCAD** [comment]
Oops, looks like you already did!

**Pull request merged**
