### PR TITLE
Androidx dependency notations big update

### PR DESCRIPTION
**Pull request by LouisCAD**
This PR adds KDoc for AndroidX dependency notations, and new dependency notations.

### CODE REVIEW

**Review by jmfayard — APPROVED** [review]

**Comment by jmfayard** [comment]
My god!

**Comment by LouisCAD** [comment]
I'm barely halfway. I'll be very grateful if you (or anyone) can help me in a pairing session where we can type faster and review together.

**Comment by LouisCAD** [comment]
109 one left to document out of 320 (not including some that I removed along the way) 🥲

**Comment by imashnake0** [comment]
> I'm barely halfway. I'll be very grateful if you (or anyone) can help me in a pairing session where we can type faster and review together.

@LouisCAD I'd love to help out but I'm not sure how useful it will be since I'm fairly inexperienced. I had to update some of the AndroidX dependencies we use at work recently so I am kind of familiar with where the release notes are. Do you have conventions/templates in place? Perhaps you could give me a brief overview of what you are trying to accomplish?

**Comment by LouisCAD** [comment]
@imashnake0 If you look at the changes in the `AndroidX.kt` from this PR, you'll see what I'm doing.
No need for special skills or experience apart from being very thorough and noticing special cases.

If you're up to help on that through a pairing session, reach out via Kotlin Slack DM, Twitter DM, or `@louiscad` through Telegram so we find a time slot that suits both of us.

**Comment by LouisCAD** [comment]
72 left, 35 of which are into the `AndroidX.compose` family. This is out of a total of 323 so far.

That less than 23% left \o/

**Comment by LouisCAD** [comment]
37 left out of 321!

**Comment by LouisCAD** [comment]
Done! 🎉🥳🙏🎉🎉🎉🎉🎉🎉🎉

Thank you so much @imashnake0!
I'm so happy it's now complete.

Just in time for Christmas release! 🎁

**Pull request merged**
