### PR TITLE
🐛 #227 refreshVersions fails when a property is missing in versions.properties

### PR DESCRIPTION
**Pull request by jmfayard**
Before:
If the key for a property was missing, refreshVersions 0.9.5 failed with

`> Couldn't resolve version for ModuleId(group=XXX)`

After: the new key is generated
```
// versions.properties
version.org.scala-lang..scala-compiler=2.13.3
```

### CODE REVIEW

**Comment by LouisCAD** [comment]
I'll check this against the history this weekend to see what changed exactly and if it's the right fix (but I think you found it right where it is).

**Comment by jmfayard** [comment]
Can this be merged?

**Comment by LouisCAD** [comment]
Not yet, I need to review it and test it locally. It's in my top priorities.

**Comment by LouisCAD** [comment]
@jmfayard I still have a hard time reproducing the issue without that PR. Can you find instructions that reproduce it all the time so I can check the difference and ensure we're fixing it correctly?

**Comment by LouisCAD** [comment]
I tested locally and I can still reproduce the issue with this PR deployed on mavenLocal.

To test it, I added the following into `sample-kotlin` dependencies:

```
implementation("org.kodein.di:kodein-di:_")
```

and on Gradle import in IDEA, I get this error message:

```
Could not resolve: org.kodein.di:kodein-di:7.1.0
```

I didn't sync again because if I did, the error would go away, and the issue would no longer be reproducible for that dependency, even after removing the entry in `versions.properties`.

As long as I keep removing the `versions.properties` entry before Gradle sync, I can reproduce the issue.

We need to investigate deeper.

**Comment by LouisCAD** [comment]
Okay, I found the root cause of issue #227… and while I'm very happy that I'll be able to fix it, I'm very, very mad at Gradle's error prone API: Calling `getCredentials()` on a repository that has no password credentials is what triggers the issue.

It's very nasty because for some reason, it happens on at Gradle sync and never from command line (even if running the `prepareKotlinBuildScriptModel` task).

I'll consider open an issue for Gradle because this is not great.

I'm closing this PR and will submit another PR that actually fixes #227.

**Comment by LouisCAD** [comment]
Bad news: there's no way to workaround this issue without using internal APIs, unless we're okay dropping support for basic authenticated repos or having a way to enable/disable it on demand.

I'll see if I can get Gradle 6.7 to fix that issue to avoid disabling that feature.
Here's the bug report for reference: https://github.com/gradle/gradle/issues/14694

**Pull request closed without merging**
