### PR TITLE
Add the regular stdlib, picasso and sqldelight

### PR DESCRIPTION
**Pull request by martinbonnin**
Adding a few more libs to the dependencies

### CODE REVIEW

**Comment by LouisCAD** [comment]
Hello, new development is happening on the develop branch (this PR points to master). The dependencies plugin is getting renamed to refreshVersions (and future old refreshVersions will be named refreshVersions-core). That means I cannot merge this PR.

Do you want to make a new one in the new directory (plugins/refreshVersions) or shall I do it myself as part of #138?

**Comment by martinbonnin** [comment]
Go for it, looks like there's already a checkbox in #138 for most of these.

**Comment by LouisCAD** [comment]
They are now all available on the develop branch, I marked you as co-author.

**Comment by LouisCAD** [comment]
FYI, I [replaced](https://github.com/jmfayard/refreshVersions/commit/e86629b5edd5087a0d9c4a08537ddde044e04d98) `Kotlin.stdlib.base` by `Kotlin.stdlib` in dev version 0.9.5-dev-011 (just published on bintray).

**Pull request closed without merging**
