### PR TITLE
Add navigation testing

### PR DESCRIPTION
**Pull request by timrijckaert**
## 🚀 Description
Adding the missing `androidx.navigation:navigation-testing` library

## 📄 Motivation and Context
Missing library

## 🧪 How Has This Been Tested?
`./gradlew test` ✅

## 📦 Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist
- [x] I have read the [guidelines for the development process](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-process/)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by LouisCAD** [comment]
Hello, please, never rebase on the main branch, it messes up history. Use merge next time, if needed (it's not needed here).

Also, see the contributing guide about dependency notations, we take issues but not PRs for these.

I'll add the dependency notation myself on the main branch.

**Comment by LouisCAD** [comment]
You need to run tests in the `:plugins:refreshVersions` project, you will see a file being edited. That change needs to be committed as well.

**Comment by timrijckaert** [comment]
Done!

**Comment by timrijckaert** [comment]
@LouisCAD could this be merged please, seems like a small change....

**Comment by LouisCAD** [comment]
Hello, I'll make a minor release this weekend including this PR. Sorry for the delay.

**Comment by jmfayard** [comment]
@timrijckaert I've fixed what was causing te CI to fail.
Thanks for your contribution! 

🎉

**Pull request merged**
