### PR TITLE
use wrapper tasks, fix #357

### LINKED ISSUE #357: Replace duplicated gradle wrappers by symlink and add samples CI check for 6.3+

### PR DESCRIPTION
**Pull request by NikkyAI**
## 🚀 Description

removed `gradlew`/`gradle` symlinks from sample projects
instead added the wrapper task

changed CI to always use the wrappers in `plugins/`

idea will automatically create the `gradlew` file and `gradle/` folders when linking the gradle projects
and also add it to `.git/info/exclude` (local gitignore) so it will nto commit duplicates
... at least on my systems

## 📄 Motivation and Context

fixes #357
symlinks end up as plain files on windows,making it impossible to develop without replacing the symlinks with real files, which messes with git diffs

## 📦 Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [x] I have read the [guidelines for the development process](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-process/)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by LouisCAD** [comment]
Can you undo the changes to the versions.properties files? They are unrelated to the change and make review and history complicated.

**Comment by NikkyAI** [comment]
i did not even realize i comitted them accidentally

**Comment by LouisCAD** [comment]
Using the commit tool window in IntelliJ can help to check what is included in the impeding commit

**Comment by jmfayard** [comment]
> idea will automatically create the gradlew file and gradle/ folders when linking the gradle projects
> and also add it to .git/info/exclude (local gitignore) so it will nto commit duplicates

That part doesn't work to me. How is that supposed to work?

**Comment by LouisCAD** [comment]
@jmfayard Did you try this PR, it did you try something else?

**Comment by jmfayard** [comment]
now replaced with https://github.com/jmfayard/refreshVersions/pull/626

**Pull request closed without merging**
