### PR TITLE
[Issue-238] Add Koin

### PR DESCRIPTION
**Pull request by brady-aiello**
This addresses the Koin part of this issue: https://github.com/jmfayard/refreshVersions/issues/238

## 🚀 Description
Add the Koin dependencies. I think the organization makes sense when referencing how [Koin docs](https://insert-koin.io/docs/setup/v3) break it up.

## 📄 Motivation and Context
Koin is a common DI / Service Locator framework for KMP, and we'd like
to migrate to refreshVersions completely.
https://insert-koin.io/docs/setup/v3
How we're using it for safe multithreading on native in KaMP Kit:
https://github.com/touchlab/KaMPKit/blob/main/shared/src/commonMain/kotlin/co/touchlab/kampkit/Koin.kt

## 🧪 How Has This Been Tested?
- `./gradlew :refreshVersions:check`
- verified that the coordinates are generated in
  `dependencies-mapping-validated.txt` and
`bundled-dependencies-validated.txt`.

## 📦 Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## ✅ Checklist

- [X] I have read the [guidelines for the development process](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dev-process/)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Comment by jmfayard** [comment]
Hello @brady-aiello 
Sorry for the late reply. 
The reason of the delay is this warning that is still on the website:

> we are in the process of refactoring the way we define dependency notations in refreshVersions, so it’s less overhead for both you and us, and less error-prone to do overall (especially regarding backwards and forward compatibility).
> That means that we’re unlikely to accept any submission of dependency notation updates for now.

Now the good news is that I've just completed this process of refactoring, it's merged in main and I would be happy to merge your 3 pull requests.

Would you mind updating them so that they use the new `DependencyGroup` API?
It's all explained here:
https://github.com/jmfayard/refreshVersions/blob/main/docs/contributing/submitting-prs/dependency-notations-updates.md

**Comment by brady-aiello** [comment]
Sounds good! I'm on vacation now, but I'll put it up by next Friday at the latest. Cheers.

**Comment by LouisCAD** [comment]
Hello Brady, we updated the contribution docs to add a guide dedicated specifically for dependency notations, available here:
https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/

Do you want to update your PR so it uses the new API we made?

**Comment by brady-aiello** [comment]
Yes, sorry for the delay. Will update tonight.

**Comment by brady-aiello** [comment]
Closing this and starting fresh with https://github.com/jmfayard/refreshVersions/pull/421

**Pull request closed without merging**
