### PR TITLE
:refreshVersionsCatalog generates a Versions Catalog

### LINKED ISSUE #169: Semi-automatic migration
For big projects, the migration can be time consuming. 
It would be great if this could be automated.

### LINKED ISSUE #333: Add support for Gradle 7.4 Version Catalogs
Gradle 7.0 introduced the "[centralized declaration of dependencies](https://docs.gradle.org/7.0/release-notes.html#centralized-dependency-versions)".
Namely, dependencies can be aliased, grouped, and versioned in a TOML file.
It would be incredibly nice if refreshVersions could target the `libs.versions.toml` file in future, rather than relying on a custom `version.properties`.

## Update: notes from jmfayard

the plan for now is not to give up `versions.properties`

it's to auto-generate the libraries versions catalog, with the placeholder version `_` and use the typesafe accessors to help migrate an existing project to refreshVersions

Running `$ ./gradlew refreshVersionsCatalog` would

   - Enable catalog version if necessary

```
// Enable Gradle's version catalog support
// https://docs.gradle.org/current/userguide/platforms.html
enableFeaturePreview("VERSION_CATALOGS")
```

   - Generate versions.properties, with all version keys (marked as unused)
   - Generate `gradle/libs.dependencies.toml`
   - Use the IDE and auto-completion to replace hardcoded dependencies with refreshVerion's dependency notations and versionCatalog or buildSrc/Libs.kt
   - To help with this, this task will show which typesafe accessors are available `$ ./ gradlew refreshVersionsMapping`

```
androidx.car:car                             | AndroidX.car
com.retrofit:retrofit-converter-json          | Square.retrofit.converter.json
org.koin:koin                                  |  libs.koin
```

Documentation

- [Sharing dependency versions between projects](https://docs.gradle.org/7.0-rc-1/userguide/platforms.html#sub:central-declaration-of-dependencies)
- [Cédric Champeau's blog: Simplified version management with Gradle 7](https://melix.github.io/blog/2021/03/version-catalogs.html)
- [tivi/libs.versions.toml at 4e378d36d37a878060bc824ab63adcc5408b203b · chrisbanes/tivi](https://github.com/chrisbanes/tivi/blob/4e378d36d37a878060bc824ab63adcc5408b203b/gradle/libs.versions.toml)

### PR DESCRIPTION
**Pull request by jmfayard**
Closes #333 

If your project is using Gradle 7.0, you can use instead [Gradle versions catalog](https://docs.gradle.org/current/userguide/platforms.html)

```bash
$ ./gradlew refreshVersionsCatalog

> Task :refreshVersionsCatalog
        new file:   gradle/libs.versions.toml
        modified:   settings.gradle.kts
        modified:   versions.properties
``` 

The generated versions catalog looks like this:

```toml
## Generated by $ ./gradlew refreshVersionsCatalog

[libraries]

browser = "androidx.browser:browser:_"

cardview = "androidx.cardview:cardview:_"

okhttp = "com.squareup.okhttp3:okhttp:_"

junit = "junit:junit:_"
```

Like with buildSrcLibs, you get type-safe accessors available in the IDE:

refreshVersions_–_build_gradle_kts__sample-kotlin_

### CODE REVIEW

**Comment by LouisCAD** [comment]
@jmfayard 'll try to review it on Saturday.

With Whit Monday, I should have time to check it over the weekend anyway.

**Comment by jmfayard** [comment]
The main thing missing is a doc on how to migrate an existing project to refreshVersions + (dependencyNotation | versionsCatalog | buildSrc)

We can do a pair-programming session this week-end if you want

**Comment by jmfayard** [comment]
Not part of this pull request:
- the task `refreshVersions` should update the metadata `## unused`
- the task `refreshVersionsMissingEntries` does not yet add entries for the plugins I had to do it manually in https://github.com/kotest/kotest/pull/2280

**Comment by jmfayard** [comment]
the task refreshVersionsMissingEntries now does add entries for the plugins 🎉

That one was hard

**Comment by jmfayard** [comment]
We decided to not merge that for now

**Pull request closed without merging**
