### PR TITLE
[Issue-518] Dependency notations for Apollo Kotlin

### LINKED ISSUE #518: Dependency notations for  apollographql/apollo-kotlin
## About the library(-ies)

- *Description*: GraphQL client that generates Kotlin and Java models from GraphQL queries.
- *GitHub*: [apollographql/apollo-kotlin](https://github.com/apollographql/apollo-kotlin)
- *Official website* (if any, besides the GitHub page): [apollographql.com/docs](https://www.apollographql.com/docs/)

## Want to contribute the sample?

- Say so in a comment here
- Follow [instructions for submitting dependency notations](https://jmfayard.github.io/refreshVersions/contributing/submitting-prs/dependency-notations-updates/)
- Submit your pull request!

### PR DESCRIPTION
**Pull request by thederputy**
Hello/bonjour, this adds a dependency notation for artifacts in the [Apollo Kotlin](https://github.com/apollographql/apollo-kotlin) project.

## What?

Resolves #518 

Adds new dependencies for Apollo

## Why?

To resolve #518 

## How?

Discussed with both @LouisCAD and @martinbonnin on naming conventions and artifacts to include.

## Testing?

- Ran ./gradlew check
- Published to maven local, and consumed in a project locally
- Tested all dependencies using `sample-android`, `sample-groovy`, and `sample-kotlin`

### CODE REVIEW

**Comment by jmfayard** [comment]
Hello, thanks for your work and especially taking the time adding KDOC with URLs, I know this is not fun but it pays off for our users.

The PR looks good. 
The only thing I'm not sure is the name of the top-level object.
It could also be `GraphQL` for example.
Then we would have `GraphQL.apollo`, `GraphQL.java`  and `GraphQL.kotlin` sharing one top-level object.
What do you think @LouisCAD ?

**Comment by LouisCAD** [comment]
I don't like too generic names like `GraphQL.kotlin`, especially when they are not authored by either Kotlin or GraphQL.

**Comment by jmfayard** [comment]
You're right, the name of the library is `graphql-kotlin` and should stay like that.
`Networking.graphqlKotlin` ?

**Comment by thederputy** [comment]
I'm happy to take the naming in the direction either of you suggest. Please let me know what is the preferred name and I will update the PR accordingly.

**Comment by LouisCAD** [comment]
Let's keep it that way for now, I'll take some time to think about it next week and see if we change it before merging.

In the meantime, @thederputy, could you please update this branch as described in the link below?

https://github.com/jmfayard/refreshVersions/pull/611#issuecomment-1250376850

**Comment by thederputy** [comment]
@LouisCAD done and updated!

**Comment by LouisCAD** [comment]
> You're right, the name of the library is `graphql-kotlin` and should stay like that. `Networking.(apollo|graphqlKotlin)` ?

What would that mean for `Square.okHttp3`, `Ktor`, `Square.retrofit`…?

I'm not sure about grouping these at all.

@jmfayard If you're okay with this PR, I suggest merging it, and consider other GraphQL libraries if people request the dependency notations.

**Comment by jmfayard** [comment]
I'm OK with merging this PR and discussing off line what should be a top-level dependency and what should be grouped within a top-level object. @LouisCAD

**Comment by jmfayard** [comment]
Thanks a lot @thederputy

**Comment by thederputy** [comment]
Thanks to you both for maintaining such a helpful tool! I'm happy to contribute where I can.

**Pull request merged**
