### PR TITLE
Add Koin

### PR DESCRIPTION
**Pull request by starsep**
Part of #238
Based on https://github.com/jmfayard/refreshVersions/pull/253/commits/4540bc8ff3741e7c87f636797817f13a698a07ea
I fixed typos, changed formatting, and applied camelCase.

List of user-facing dependencies is here: https://github.com/InsertKoinIO/koin#core-features

### CODE REVIEW

**Comment by starsep** [comment]
@jmfayard Can you tell me the reasons of closing this PR?
I see that you deleted `jmfayard:master` branch, should I target `main` or `develop`?
I am happy to make any necessary changes and make a new PR.
If you are already working on it that's fine as well - just let me know.

**Comment by LouisCAD** [comment]
Hi @starsep, we are in a state where we cannot easily accept contributions for several reasons.

We'll fix that and put an up to date contributing guide soon, and we'll have Koin among the dependency notations, rest assured.

**Comment by starsep** [comment]
@LouisCAD
Version 0.10.0 has been released.
Is it good time to add Koin now?
They recently moved to mavenCentral and changed their maven group id from org.koin to io.insert-koin.
Is the contributing guide up to date?
I assume I should follow https://jmfayard.github.io/refreshVersions/contributing/submitting-issues/ and https://jmfayard.github.io/refreshVersions/contributing/before-you-contribute/

**Comment by LouisCAD** [comment]
Right now, it's a good time to sleep for me after spending the night on the laat steps of the release, but yes, we'll add some more dependency notations in the coming releases in the coming days (we should be able to release way more often now).

Thanks for the info about koin coordinates that changed. Probably a good thing that we didn't have the dependency notations before then, it avoids us having to do a complicated migration.

**Comment by LouisCAD** [comment]
About the contributing guide, yes, it's up to date, but look closely, there's a section about dependency notations where it says we're not accepting PRs for it for now.

**Pull request closed without merging**
