### PR TITLE
Add Spring.boot.web notation

### LINKED ISSUE #610: Dependency notations for Spring Boot Starter Web
## About the library(-ies)

- *Description*: Spring boot modules are already present; starter web is missing

## Want to contribute the sample?

- I will do a PR

### PR DESCRIPTION
**Pull request by Gounlaf**
Hello/bonjour,

## What?

Resolves #610 

## Testing?

~~CI Errors are not related to my changes (if I'm right)~~

### CODE REVIEW

**Comment by LouisCAD** [comment]
Hi, they are. Please look at the contributing guide on our website.

**Review by LouisCAD — APPROVED** [review]

**Review by jmfayard — APPROVED** [review]

**Comment by Gounlaf** [comment]
@LouisCAD can you confirm me I need to rebase and remove some file because of #614 ?

**Comment by LouisCAD** [comment]
Yes, the exact steps for you to follow are:

1. Undo commit (keeping your changes)
2. Remove the changes to the `docs/dependencies-notations.md` file
3. Update/rebase your branch
4. Commit back
5. Force-push

**Comment by Gounlaf** [comment]
> @Gounlaf Yes, the exact steps for you to follow are:
> 
>     1. Undo commit (keeping your changes)
>     2. Remove the changes to the `docs/dependencies-notations.md` file
>     3. Update/rebase your branch
>     4. Commit back
>     5. Force-push

@LouisCAD Thanks for your quick answer. It sould be ok.

**Comment by LouisCAD** [comment]
It is, thank you!

**Pull request merged**
