### PR TITLE
API refreshVersions.rejectVersionIf { ... }

### PR DESCRIPTION
**Pull request by jmfayard**
About #343
Sometimes hundreds of dev versions are proposed by refreshVersions

It's what I had implemented in the Gradle Versions plugin
and it works well there

https://github.com/ben-manes/gradle-versions-plugin

### CODE REVIEW

**Comment by LouisCAD** [comment]
I don't think this is the right design route because it makes it easy to filter all dependencies, potentially throwing the baby out with the bath water.

Also, regarding the example, it's important to note that we have a built-in way to know the stability level of a version.

Let's talk about it later and write all the options we could provide so we make.

**Comment by jmfayard** [comment]
Yup, let's talk about it and see what are the use cases for such a feature

**Comment by jmfayard** [comment]
@LouisCAD have a look at the updated PR, I improved the design and find it both simple and powerful
The filter is now not only declared but also implemented
I've tried it out on the kotlin-libraries-playground  https://github.com/LouisCAD/kotlin-libraries-playground/commit/e3838f16bb0cda35caadad030b8198742ff12bfb

**Comment by LouisCAD** [comment]
One thing we could do is automatically add a comment in the `versions.properties` when there's code affecting the versions "acceptance".

For example:
```properties
## NOTE: Some versions are filtered by the rejectVersionsIf predicate. See the settings.gradle.kts file.
```

The `.kts` part would be dropped if we see the settings file is using Groovy DSL.

That way, people won't be surprised about versions not showing up, even if they just landed in the project.

**Comment by jmfayard** [comment]
I'm fine with that!

On July 29, 2021, Louis CAD ***@***.***> wrote:
> One thing we could do is automatically add a comment in the
> versions.properties when there's code affecting the versions
> "acceptance".
>
> For example:
>
> ## NOTE: Some versions are filtered by the rejectVersionsIf predicate.
> See the settings.gradle.kts file.
> The .kts part would be dropped if we see the settings file is using
> Groovy DSL.
>
> That way, people won't be surprised about versions not showing up,
> even if they just landed in the project.
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/jmfayard/refreshVersions/pull/347#issuecomment-
889228668>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AADQFSHXZINZW7D22LAFSD3T2FVSJANCNFSM443KE73Q>.

**Comment by jmfayard** [comment]
@LouisCAD Thinking about it it might be better to put the warning in the console log instead of the header.
As you said the header is only read once when it changes. If multiple people work on a project, only one will see the change, versus everyone if it's in the console log.

Also I'm pretty sure I can give the number of filtered versions instead of saying "some versions"

`NOTE: 172 versions are filtered by the rejectVersionsIf predicate. See the settings.gradle.kts file.`

**Comment by LouisCAD** [comment]
@jmfayard I didn't say only one person would see it, I said once you see it in a project, you ignore it for next times.

I also think logs are more likely to be ignored than a comment, which can also be seen into the git diff.

I think adding a comment as I initially suggested is very important, and an informational or warning log could be a good addition if it tells how many version entries are affected, and how many newer versions are filtered out (as you implied with your example). That'd make it easy to spot if the predicate affects more version entries than expected.

**Comment by jmfayard** [comment]
@LouisCAD I've implemented both the file comment and the log comment, ready to review

**Comment by jmfayard** [comment]
I added the docs, this is ready to merge IHMO @LouisCAD

**Pull request merged**
