### PR TITLE
Update Google accompanist modules

### PR DESCRIPTION
**Pull request by rlatapy-luna**

### CODE REVIEW

**Comment by rlatapy-luna** [comment]
> Hello, thanks for the PR.
> 
> Why did you revert changes to test resources?

Hello, I thought it was breaking the test 🤔

**Comment by jmfayard** [comment]
@rlatapy-luna  nope the tests are here to prevent you from typos and so on.

It seems that there are more libraries than what your PR contains. 
https://mvnrepository.com/search?q=com.google.accompanist

Can you add them too and run the tests please?

**Comment by rlatapy-luna** [comment]
> Can you add them too and run the tests please?

I added missing accompanist lib and removed deprecated ones (glide & imageloadingCore)

**Comment by LouisCAD** [comment]
Thanks for updating!
I'll review it soon.

**Review by LouisCAD — APPROVED** [review]
It was nicely done, thank you!

I had to rebase onto main and redo the removals tracking because I did further changes before taking on to this PR, should have merged this first 😅

**Pull request merged**
