### PR TITLE
Add Square.leakCanary constant

### PR DESCRIPTION
**Pull request by OscarSpruit**
## Issue
#208 

## What type of PR is this? (check all applicable)

- [ ] Refactor
- [x] Feature
- [ ] Bug Fix
- [ ] Documentation Update

## Description
Added `Square.leakCanary` constant to support the three most relevant LeakCanary dependencies.

### CODE REVIEW

**Comment by LouisCAD** [comment]
Thanks for the PR! I discovered a few more LeakCanary dependencies by reviewing its documentation, and I think these are worth adding, so I added them.

**Comment by OscarSpruit** [comment]
Nice! I believe there are even more, but I'm not sure which are needed and which not 🤔

**Comment by LouisCAD** [comment]
Hello @pyricau, can you tell us if other artifacts are missing?

I looked at [maven central search here](https://search.maven.org/search?q=g:com.squareup.leakcanary), but I'm unsure which ones should be filtered out because not designed for public use (but only as transitive dependencies of public-use designed artifacts).

**Comment by LouisCAD** [comment]
Merged this. Will add links in KDoc, and the gradle plugin dependency in upcoming commits.

**Pull request merged**
